<a href="https://colab.research.google.com/github/HINITAPRIYANKA/Scifor/blob/main/Numpy_Hinitapriyanka_S.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

import re

In [ ]:
import numpy as np
import re

data = np.array(['apple', 'banana', 'cherry', 'date'])

pattern = re.compile(r'a.*')

vectorized_function = np.vectorize(lambda x: bool(pattern.match(x)))

result = vectorized_function(data)

print(result)


[ True False False False]


creating numpy array

In [ ]:
import numpy as np

# Create a 1D array
arr1 = np.array([1, 2, 3, 4, 5])

# Create a 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("1D array:")
print(arr1)

print("\n2D array:")
print(arr2)


1D array:
[1 2 3 4 5]

2D array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Array operations

In [ ]:
import numpy as np

# Create two arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result_add = arr1 + arr2
result_subtract = arr2 - arr1
result_multiply = arr1 * arr2
result_divide = arr2 % arr1

print("Addition:")
print(result_add)
print("\n Subtraction:")
print(result_subtract)
print("\n Multiplication:")
print(result_multiply)
print("\n Division:")
print(result_divide)


Addition:
[5 7 9]

 Subtraction:
[3 3 3]

 Multiplication:
[ 4 10 18]

 Division:
[0 1 0]


Array indexing and slicing

In [ ]:
import numpy as np

# Create a 1D array
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Access individual elements
print("Element at index 3:", arr[3])

# Slice the array
print("Slice from index 2 to 6:", arr[2:7])

# Reverse the array
print("Reversed array:", arr[::-1])


Element at index 3: 3
Slice from index 2 to 6: [2 3 4 5 6]
Reversed array: [9 8 7 6 5 4 3 2 1 0]


Statistical operations

In [ ]:
import numpy as np

# Create an array
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Calculate mean, median, and standard deviation
mean_value = np.mean(data)
median_value = np.median(data)
std_deviation = np.std(data)

print("Mean:", mean_value)
print("Median:", median_value)
print("Standard Deviation:", std_deviation)
